# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91f49050dc1a0ebc7c043456f5607100d2ed51afcfc8e0e9d13a660d6793dde58d82d9416157ef6573cca353acc9abe1b8ead56050be3f18e4639e84d6a3b9ca

test:
  secret_key_base: ede6b3178e610b26e0a3053154177cef5a189e1fecb75b25bc09099055c3010e967f7f44e90e372d93889f00d029c4dc5328b01c1a90d682341c12d315f1836f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
